import { Github, Mail, MessageCircleMore } from "lucide-react";
import { ContactForm } from "@/components/impact/contact-form";
import { TeamGrid } from "@/components/impact/team-grid";
import { InstituteNav } from "@/components/institute/institute-nav";
import { pageMetadata } from "@/lib/metadata";

export const metadata = pageMetadata("Research Team & Contact", "Meet the student researchers advancing transparency at Impact500.", "/team");

export default function TeamPage() {
  const opportunities = ["Academic Research", "Educational Partnerships", "Student Research Initiatives", "Media Inquiries", "Speaking Opportunities", "Research Collaborations", "Platform Feedback"];
  return <main>
    <section className="lovable-hero border-b"><div className="page-shell pb-20 pt-10"><InstituteNav /><p className="mt-16 text-xs font-semibold uppercase tracking-[.28em] text-emerald-400">Meet our research team</p><h1 className="display mt-6 max-w-5xl text-5xl leading-[.98] sm:text-7xl lg:text-[5.2rem]">Research built through collaboration.</h1><p className="mt-8 max-w-4xl text-xl leading-9 text-slate-300">Behind Impact500 is a multidisciplinary team of student researchers committed to advancing transparency in corporate responsibility.</p><p className="mt-4 max-w-4xl text-lg leading-8 text-slate-400">Together, the team analyzes publicly available corporate disclosures, develops evaluation frameworks, validates research findings, and contributes to the continuous improvement of the Impact500 methodology. Every researcher plays an important role in maintaining the consistency, accuracy, and integrity of the platform&apos;s evaluations.</p></div></section>
    <div className="page-shell space-y-24">
      <section><SectionIntro eyebrow="Our researchers" title="The people behind the evidence." /><div className="mt-12"><TeamGrid /></div></section>
      <section className="surface-card grid gap-8 lg:grid-cols-[.65fr_1.35fr]"><div><p className="text-xs uppercase tracking-[.2em] text-cyan">Our collaborative approach</p><h2 className="display mt-5 text-4xl">Consistency through collective review.</h2></div><p className="text-lg leading-8 text-slate-300">Impact500&apos;s research is built through collaboration. Researchers work together to collect publicly available information, validate findings, compare corporate disclosures, and continuously improve the evaluation framework. This collaborative process helps ensure consistency, transparency, and methodological integrity across every company profile.</p></section>
      <section><SectionIntro eyebrow="Contact Impact500" title="Start a conversation." text="We welcome inquiries regarding our research, methodology, educational initiatives, and potential collaborations. Whether you’re a student, educator, researcher, journalist, or business professional, we’d love to hear from you." /><div className="mt-12 grid gap-6 lg:grid-cols-[.72fr_1.28fr]"><div className="space-y-5"><article className="surface-card"><Mail className="size-6 text-cyan" /><p className="mt-6 text-xs uppercase tracking-wider text-slate-500">Research email</p><a href="mailto:research@impact500.org" className="mt-2 block text-lg font-semibold text-white hover:text-cyan">research@impact500.org</a></article><article className="surface-card"><Github className="size-6 text-cyan" /><p className="mt-6 text-xs uppercase tracking-wider text-slate-500">GitHub</p><a href="https://github.com/dshetty2498-hue/Impact-500" target="_blank" rel="noreferrer" className="mt-2 block break-all text-sm font-semibold text-white hover:text-cyan">dshetty2498-hue/Impact-500</a></article></div><ContactForm /></div></section>
      <section className="grid-bg rounded-[2rem] border bg-accent/10 p-8 md:p-12"><MessageCircleMore className="size-7 text-cyan" /><SectionIntro eyebrow="Collaborate with us" title="Contribute to better public research." text="Impact500 welcomes thoughtful opportunities that strengthen research, education, and public understanding." /><div className="mt-10 flex flex-wrap gap-2">{opportunities.map((item) => <span key={item} className="rounded-full border bg-ink/60 px-4 py-2 text-sm text-slate-300">{item}</span>)}</div><a href="mailto:research@impact500.org?subject=Impact500%20collaboration" className="button-primary mt-8">Contact Us <Mail className="size-4" /></a></section>
    </div>
  </main>;
}

function SectionIntro({ eyebrow, title, text }: { eyebrow: string; title: string; text?: string }) { return <div className="max-w-4xl"><p className="text-xs font-semibold uppercase tracking-[.24em] text-cyan">{eyebrow}</p><h2 className="display mt-5 text-4xl leading-[1.02] md:text-6xl">{title}</h2>{text && <p className="mt-6 text-lg leading-8 text-slate-400">{text}</p>}</div>; }
