import { ArrowRight, BookOpen, Building2, GraduationCap, HandHeart, Users } from "lucide-react";
import { InstituteNav } from "@/components/institute/institute-nav";
import { SectionTitle } from "@/components/ui/primitives";
import { pageMetadata } from "@/lib/metadata";

export const metadata = pageMetadata("Partnerships", "Collaborate with the Impact500 research initiative.", "/partnerships");

const paths = [[GraduationCap, "Academic partnerships", "Course collaborations, methods review, student research, and shared public-interest scholarship."], [Building2, "Business engagement", "Evidence clarification and structured dialogue without influence over scoring or editorial conclusions."], [BookOpen, "Research partnerships", "Subject-matter review, source development, sector expertise, and co-published analysis."], [HandHeart, "Volunteer opportunities", "Source verification, accessibility review, data quality, and community outreach."], [Users, "Guest researchers", "Time-bound research contributions with visible authorship and conflict-of-interest disclosure."], [ArrowRight, "Future sponsors", "Mission-aligned support governed by editorial independence and public transparency."]] as const;

export default function PartnershipsPage() {
  return <main className="page-shell"><InstituteNav /><SectionTitle eyebrow="Partnerships" title={<>Build better public evidence, <em className="text-cyan">together.</em></>} text="Impact500 welcomes collaborations that strengthen research quality, public access, and responsible use while preserving editorial independence." /><section className="mt-14 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{paths.map(([Icon, title, text]) => <article key={title} className="premium-card"><Icon className="size-6 text-cyan" /><h2 className="mt-8 text-2xl font-semibold">{title}</h2><p className="mt-4 leading-7 text-zinc-400">{text}</p></article>)}</section><section className="mt-16 grid gap-6 lg:grid-cols-[1fr_.8fr]"><article className="surface-card"><p className="text-xs uppercase tracking-wider text-cyan">Partnership principles</p><ul className="mt-6 grid gap-4 sm:grid-cols-2">{["Editorial independence", "Disclosed conflicts", "Public-interest purpose", "Methodological transparency", "Respect for participants", "No pay-to-rank arrangements"].map((item) => <li key={item} className="rounded-xl border bg-ink/50 p-4 text-sm text-slate-300">{item}</li>)}</ul></article><article className="grid-bg rounded-[1.5rem] border bg-accent/10 p-8"><p className="text-xs uppercase tracking-wider text-cyan">Start a conversation</p><h2 className="mt-5 text-3xl font-semibold">Tell us what you want to investigate.</h2><p className="mt-4 leading-7 text-zinc-400">Include your organization, proposed contribution, timeframe, and any relevant conflicts.</p><a href="mailto:research@impact500.org" className="button-primary mt-8">Contact the institute <ArrowRight className="size-4" /></a></article></section></main>;
}
