"""Generate the centralized 2026 Fortune 500 leadership seed.

The input is a saved copy of the public table at
https://www.demandsage.com/fortune-500-companies/. The generated file is data,
not page-specific UI content; all product surfaces consume it through the
platform repository.
"""

from __future__ import annotations

import html
import json
import re
import sys
from pathlib import Path


SOURCE = Path(sys.argv[1] if len(sys.argv) > 1 else "/tmp/fortune500-2026.html")
SP500_SOURCE = Path(sys.argv[2] if len(sys.argv) > 2 else "/tmp/sp500-ceos.html")
TARGET = Path("data/fortune-500-2026.generated.ts")


def clean(value: str) -> str:
    value = re.sub(r"<[^>]+>", "", value)
    return " ".join(html.unescape(value).replace("\xa0", " ").split())


document = SOURCE.read_text(encoding="utf-8")
tables = re.findall(r"<table[\s\S]*?</table>", document, flags=re.IGNORECASE)
records: list[list[object]] = []

for table in tables:
    for row in re.findall(r"<tr[\s\S]*?</tr>", table, flags=re.IGNORECASE):
        cells = [
            clean(cell)
            for cell in re.findall(
                r"<t[dh][^>]*>([\s\S]*?)</t[dh]>", row, flags=re.IGNORECASE
            )
        ]
        if len(cells) != 6 or not cells[0].isdigit():
            continue
        rank, company, revenue, industry, state, ceo = cells
        revenue_millions = float(re.sub(r"[^0-9.]", "", revenue) or 0)
        records.append(
            [int(rank), company, revenue_millions, industry, state, ceo, "baseline"]
        )


def company_key(value: str) -> str:
    value = value.lower().replace("&", " and ")
    value = re.sub(
        r"\b(?:incorporated|inc|corporation|corp|company|co|group|holdings|holding|plc|the|class [ac])\b",
        "",
        value,
    )
    return re.sub(r"[^a-z0-9]", "", value)


if SP500_SOURCE.exists():
    sp500_document = SP500_SOURCE.read_text(encoding="utf-8")
    sp500_leaders: dict[str, str] = {}
    for row in re.findall(r"<tr[\s\S]*?</tr>", sp500_document, flags=re.IGNORECASE):
        cells = [
            clean(cell)
            for cell in re.findall(
                r"<td[^>]*>([\s\S]*?)</td>", row, flags=re.IGNORECASE
            )
        ]
        if len(cells) >= 7 and cells[0].isdigit():
            sp500_leaders[company_key(cells[2])] = cells[4]
    for record in records:
        cross_checked = sp500_leaders.get(company_key(str(record[1])))
        if cross_checked:
            record[5] = cross_checked
            record[6] = "sec-cross-check"

records.sort(key=lambda item: int(item[0]))
if len(records) != 500:
    raise SystemExit(f"Expected 500 company rows, found {len(records)}")
ranks = [int(record[0]) for record in records]
if ranks != sorted(ranks) or ranks[0] != 1 or ranks[-1] != 500:
    raise SystemExit("Ranks must be ordered and span 1-500 (published ties are allowed)")

placeholders = re.compile(r"^(?:unknown|n/?a|not yet verified|ceo tbd)?$", re.I)
invalid = [record for record in records if placeholders.fullmatch(str(record[5]).strip())]
if invalid:
    raise SystemExit(f"Invalid CEO values: {invalid}")

lines = [
    "// Generated by scripts/generate_fortune_2026.py.",
    "// Fortune membership/rank source: Fortune 500 (2026).",
    "// Baseline leadership source checked 2026-08-22; official-source overrides live in data/platform.ts.",
    "",
    "export type Fortune2026Seed = readonly [",
    "  rank: number,",
    "  name: string,",
    "  revenueMillions: number,",
    "  industry: string,",
    "  headquartersState: string,",
    "  chiefExecutive: string,",
    '  leadershipSource: "baseline" | "sec-cross-check",',
    "];",
    "",
    "export const fortune5002026 = [",
]
for record in records:
    lines.append(f"  {json.dumps(record, ensure_ascii=False)},")
lines.extend(
    [
        "] as const satisfies readonly Fortune2026Seed[];",
        "",
        "export const fortune500LeadershipMeta = {",
        '  fortuneYear: 2026,',
        '  leadershipCheckedAt: "2026-08-22",',
        '  rankSourceUrl: "https://fortune.com/ranking/fortune500/2026/",',
        '  baselineLeadershipSourceUrl: "https://www.demandsage.com/fortune-500-companies/",',
        '  publicCompanyCrossCheckUrl: "https://ceotracker.co.uk/sp500",',
        "  companyCount: fortune5002026.length,",
        "} as const;",
        "",
    ]
)

TARGET.write_text("\n".join(lines), encoding="utf-8")
print(f"generated {len(records)} Fortune 500 leadership records")
