import { Download, Mail, Quote } from "lucide-react";
import { InstituteNav } from "@/components/institute/institute-nav";
import { SectionTitle } from "@/components/ui/primitives";
import { pageMetadata } from "@/lib/metadata";

export const metadata = pageMetadata("Press and Media", "Impact500 media resources and institutional information.", "/media");

export default function MediaPage() {
  return <main className="page-shell"><InstituteNav /><SectionTitle eyebrow="Press and media" title={<>Resources for clear, accurate <em className="text-cyan">coverage.</em></>} text="Institutional information, approved language, brand guidance, and contacts for journalists and research partners." /><section className="mt-14 grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><article className="surface-card"><Quote className="size-7 text-cyan" /><p className="mt-8 text-xs uppercase tracking-wider text-cyan">Approved project summary</p><blockquote className="display mt-5 text-3xl leading-tight md:text-4xl">Impact500 is an independent research initiative making corporate responsibility evidence understandable, comparable, and useful.</blockquote><p className="mt-6 leading-7 text-zinc-400">The platform publishes company profiles, sector analysis, methodology, interactive research tools, and annual reports.</p></article><article className="surface-card"><p className="text-xs uppercase tracking-wider text-cyan">Press contact</p><h2 className="mt-5 text-3xl font-semibold">Media inquiries</h2><p className="mt-4 leading-7 text-zinc-400">For interviews, methodology questions, data context, or publication permissions.</p><a href="mailto:research@impact500.org" className="button-primary mt-8"><Mail className="size-4" />research@impact500.org</a></article></section><section className="mt-16"><p className="text-xs uppercase tracking-[.2em] text-cyan">Media resources</p><div className="mt-8 grid gap-5 md:grid-cols-2 xl:grid-cols-4">{[["Brand assets", "Primary wordmark, icon, and color references."], ["Media kit", "Project overview, key figures, and approved descriptions."], ["Founder biography", "Background and project-origin summary."], ["Research brief", "Methodology, coverage, and citation guidance."]].map(([title, text]) => <article key={title} className="premium-card"><div className="grid size-12 place-items-center rounded-xl border bg-ink text-cyan"><Download className="size-5" /></div><h2 className="mt-8 text-xl font-semibold">{title}</h2><p className="mt-4 text-sm leading-7 text-zinc-400">{text}</p><span className="mt-7 block text-xs text-slate-500">Available by request</span></article>)}</div></section><section className="surface-card mt-16"><p className="text-xs uppercase tracking-wider text-cyan">Brand use</p><p className="mt-4 max-w-4xl leading-7 text-zinc-400">Use the Impact500 name accurately, do not imply endorsement, preserve the logo’s proportions, and attribute published research to the Impact500 Institute with a direct link to the cited page.</p></section></main>;
}
